### ISSUE TITLE
xgboost Invalid shape of labels during evaluation

### ISSUE THREAD

**Issue by pakiessling** [theislab/spapros#261]
Hi, I am receiving the error` Check failed: info.labels.Size() == preds.Size() (14773 vs. 29546) : Invalid shape of labels` during evaluation of a panel.
The cell types I am running on:

```
adata.obs.cell_type.value_counts()
PC-S1    17463
PC-S2     1004
```
Could the problem be that there are only 2 categories?

<details>
  <summary>Full log</summary>

```
/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
Starting tucker_pericyte run
Dataset loaded
Assuming adata.X contains raw counts
AnnData object with n_obs × n_vars = 18467 × 25108
    obs: 'Cluster', 'Subcluster', 'experiment', 'chamber', 'nUMI', 'nGene', 'percent.mito.raw', 'biological.individual', 'n_genes'
    var: 'gene_ids', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'hvg'
    obsm: 'X_umap'
    layers: 'cellranger'
Dataset processed
Starting Evaluation
Panel of a length of 331

Annotation summary:
PC-S1    17463
PC-S2     1004
Name: Subcluster, dtype: int64

SPAPROS PROBESET EVALUATION:                                                    
Shared metric computations................................ ━━━━━━━   3/3 0:06:49
  Loading shared computations for knn_overlap............. ━━━━━━━  100% 0:00:00
  Loading shared computations for gene_corr............... ━━━━━━━  100% 0:06:48
Probeset specific pre computations........................ ━━━━━━━   3/3 0:00:50
  Computing pre compuations for knn_overlap............... ━━━━━━━   6/6 0:00:49
Final probeset specific computations...................... ━━        1/3 0:00:01
  Computing final compuations for knn_overlap............. ━━━━━━━   6/6 0:00:01
  Computing final compuations for forest_clfs.............          0/25 0:00:00
Traceback (most recent call last):
  File "/rwthfs/rz/cluster/work/rwth1209/projects/500_heart_panel/05_Validation/spapros_evaluate_cli.py", line 94, in <module>
    evaluator.evaluate_probeset(selection, set_id="panel1")
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/spapros/evaluation/evaluation.py", line 465, in evaluate_probeset
    raise error
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/spapros/evaluation/evaluation.py", line 418, in evaluate_probeset
    self.results[metric][set_id] = metric_computations(
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/spapros/evaluation/metrics.py", line 272, in metric_computations
    results = xgboost_forest_classification(
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/spapros/evaluation/metrics.py", line 1017, in xgboost_forest_classification
    clf.fit(
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/core.py", line 575, in inner_f
    return f(**kwargs)
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/sklearn.py", line 1400, in fit
    self._Booster = train(
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/core.py", line 575, in inner_f
    return f(**kwargs)
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/core.py", line 1778, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
  File "/rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/core.py", line 246, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [19:21:55] ../src/objective/regression_obj.cu:36: Check failed: info.labels.Size() == preds.Size() (14773 vs. 29546) : Invalid shape of labels.
Stack trace:
  [bt] (0) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/lib/libxgboost.so(+0x5afc79) [0x14f3a3935c79]
  [bt] (1) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/lib/libxgboost.so(+0x5afee6) [0x14f3a3935ee6]
  [bt] (2) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/lib/libxgboost.so(+0x5c5f5d) [0x14f3a394bf5d]
  [bt] (3) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/lib/libxgboost.so(+0x225b08) [0x14f3a35abb08]
  [bt] (4) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x68) [0x14f3a3445098]
  [bt] (5) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/lib-dynload/../../libffi.so.8(+0x6a4a) [0x14f5007d0a4a]
  [bt] (6) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/lib-dynload/../../libffi.so.8(+0x5fea) [0x14f5007cffea]
  [bt] (7) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0x132ad) [0x14f5007e92ad]
  [bt] (8) /rwthfs/rz/cluster/home/mz637064/mambaforge/envs/spapros/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0x12954) [0x14f5007e8954]
```

</details>

Btw @LouisK92 is there any news on the memory leak? There are some cool datasets I am really itching to try spapros on.

Thank you so much !

**Comment by LouisK92** [comment]
Ah yea, @strasserle you ran into that one as well, right? Did you write a fix in some (local) branch that we can push?

Wrt the memory leak: now that I can access my code of the solution again I should be able to push it the next days:)

**Comment by strasserle** [comment]
Yes, that is what I fixed. You can find it in my forked spaprosX repository at branch feature/batch-aware.

**Comment by pakiessling** [comment]
Ty @LouisK92 @strasserle

**Comment by LouisK92** [comment]
@pakiessling 
Should work now after reinstalling the newest version (0.1.3) (includes the memory leak fix).
